baseURL: /
languageCode: en-us
build:
  writeStats: true
title: aafu theme
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu

params:
  tailwind: '"npx tailwindcss"'
  author: Darshan Baral
  description: Website title
  copyright: coded by Dee
  theme:
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
    - item: projects
    - item: skills
      panel_id: skill-panel
    - item: hobbies
