baseURL: /
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 1
  de:
    languageName: Deutsch
    languageCode: de-de
    weight: 2
build:
  writeStats: true

params:
  tailwind: '"npx tailwindcss"'
  author: Diana Dee Kalstein
  description: Dee's Portfolio
  copyright: coded by Dee
  theme:
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
    - item: projects
    - item: skills
      panel_id: skill-panel
    - item: hobbies
